// ======= DO NOT EDIT THIS FILE ============
package csd201_se1610_pe2;
// ======= DO NOT EDIT THIS FILE ============
public class Book {
    String code, name, author;
    double price;
// ======= DO NOT EDIT THIS FILE ============    
    public Book(String code, String name, String author, double price) {
        this.code = code;
        this.name = name;
        this.author = author;
        this.price = price;
    }
// ======= DO NOT EDIT THIS FILE ============    
    @Override
    public String toString() {
        return String.format("%-10s%-25s%-25s%-10.2f", 
                code,name,author,price);
    }  
}
// ======= DO NOT EDIT THIS FILE ============