// ======= DO NOT EDIT THIS FILE ============
package csd201_se1610_pe2;
// ======= DO NOT EDIT THIS FILE ============
import java.util.Scanner;
// ======= DO NOT EDIT THIS FILE ============
public class Main {   
    public static void main(String[] args) {      
        Scanner s = new Scanner(System.in);
        MyList m = new MyList();
        m.loadData();      
        int choice;
        while(true) {
            System.out.println("\n Choose your option:");         
            System.out.println("  1. Add a new book");
            System.out.println("  2. Update the price of a book");
            System.out.println("  3. Remove a book");
            System.out.println("  4. List all books");
            System.out.println("  5. Sort books by book’s code");
            System.out.println("  0. Quit\n");
            System.out.print("  Your selection (0 -> 5): ");
            choice = s.nextInt();
            if(choice==0) {
                System.out.println(" Good bye, have a nice day!");
                break;
            }
            switch(choice) {
                case 1:  
                        m.addNewBook(); 
                        break;
                case 2: 
                        m.updateBook();
                        break;                        
                case 3:  
                        m.removeBook(); 
                        break;
                case 4: 
                        m.traverse();
                        break;
                case 5:  
                        m.sort();
                        break;                           
                default: System.out.println("**Invalid choice. Try again.**");
            }
        }
    }
}
// ======= DO NOT EDIT THIS FILE ============