// ======= DO NOT EDIT THIS FILE ============
package csd201_se1610_pe2;
// ======= DO NOT EDIT THIS FILE ============
public class Node {
    Book info; Node next;   
// ======= DO NOT EDIT THIS FILE ============    
    //create a new node where next is null
    public Node(Book info) {this(info,null);}
// ======= DO NOT EDIT THIS FILE ============    
    public Node(Book info, Node next) {
        this.info = info; 
        this.next = next;
    }
}
// ======= DO NOT EDIT THIS FILE ============