--1
	SELECT MASP,TENSP FROM SANPHAM WHERE NUOCSX='Trung Quoc'
--2
	SELECT MASP,TENSP FROM SANPHAM WHERE DVT IN ('cay','quyen')
--3
	SELECT MASP,TENSP FROM SANPHAM WHERE MASP LIKE 'B%01'
--4
	SELECT MASP,TENSP FROM SANPHAM 
	WHERE NUOCSX='Trung Quoc' AND GIA<40000 AND GIA>30000
--5
	SELECT MASP,TENSP FROM SANPHAM 
	WHERE (NUOCSX='Trung Quoc'OR NUOCSX='Thai Lan') AND GIA<40000 AND GIA>30000
--6
	SELECT * FROM HOADON
	WHERE NGHD IN ('2007-01-01','2007-01-02')
--7
	SELECT * FROM HOADON
	WHERE NGHD <='2007-01-31' AND NGHD>='2007-01-01'
	ORDER BY NGHD, TRIGIA DESC
--8
	SELECT * FROM HOADON
	WHERE NGHD ='2007-01-01'
--9
	SELECT * FROM HOADON
	WHERE MANV IN (SELECT MANV FROM NHANVIEN WHERE HOTEN='Nguyen Van B')
	AND NGHD='2006-10-28'
--10
	SELECT MASP, TENSP FROM SANPHAM WHERE MASP IN 
	(SELECT DISTINCT(MASP) FROM CTHD
	WHERE SOHD IN (SELECT SOHD FROM HOADON WHERE MAKH IN (SELECT MAKH FROM KHACHHANG WHERE HOTEN='Nguyen Van A' )))
--11
	SELECT DISTINCT(SOHD) FROM CTHD
	WHERE MASP IN ('BB01','BB02')
--12
	SELECT DISTINCT(SOHD) FROM CTHD
	WHERE MASP IN ('BB01','BB02')
	AND SL>=10 AND SL<=20
--13
    SELECT SOHD FROM CTHD 
    WHERE SOHD=(SELECT DISTINCT(SOHD) FROM CTHD
	WHERE MASP = 'BB01'
	AND SL>=10 AND SL<=20)
    AND MASP='BB02' AND SL >= 10 AND SL <= 20;


--14
	SELECT MASP,TENSP FROM SANPHAM 
	WHERE NUOCSX='Trung Quoc' OR MASP IN (SELECT MASP FROM HOADON, CTHD WHERE HOADON.NGHD='2007-01-01' AND CTHD.SOHD=HOADON.SOHD)
--15
	SELECT MASP,TENSP FROM SANPHAM
	WHERE MASP  NOT IN (SELECT DISTINCT(MASP) FROM CTHD )

-- 16
SELECT DISTINCT SANPHAM.MASP, SANPHAM.TENSP FROM SANPHAM
JOIN CTHD ON SANPHAM.MASP=CTHD.MASP
JOIN HOADON ON CTHD.SOHD=HOADON.SOHD
WHERE HOADON.NGHD < '2006-1-1' OR HOADON.NGHD > '2006-12-31';

-- 17
SELECT DISTINCT SANPHAM.MASP, SANPHAM.TENSP FROM SANPHAM
JOIN CTHD ON SANPHAM.MASP=CTHD.MASP
JOIN HOADON ON CTHD.SOHD=HOADON.SOHD
WHERE (HOADON.NGHD < '2006-1-1' OR HOADON.NGHD > '2006-12-31') AND SANPHAM.NUOCSX='Trung Quoc';

-- 18
SELECT HOADON.SOHD FROM HOADON
JOIN CTHD ON CTHD.SOHD=HOADON.SOHD
JOIN SANPHAM ON CTHD.MASP=SANPHAM.MASP
WHERE SANPHAM.NUOCSX='Singapore'
GROUP BY HOADON.SOHD HAVING COUNT(*) = (SELECT COUNT(*) FROM SANPHAM WHERE NUOCSX='Singapore');


-- 19
SELECT HOADON.SOHD FROM HOADON
JOIN CTHD ON CTHD.SOHD=HOADON.SOHD
JOIN SANPHAM ON CTHD.MASP=SANPHAM.MASP
WHERE SANPHAM.NUOCSX='Singapore' AND HOADON.NGHD BETWEEN '2006-1-1' AND '2006-12-31'
GROUP BY HOADON.SOHD HAVING COUNT(*) = (SELECT COUNT(*) FROM SANPHAM WHERE NUOCSX='Singapore');

-- 20
SELECT COUNT(*) FROM HOADON WHERE MAKH IS NULL;

-- 21
SELECT COUNT(DISTINCT SANPHAM.MASP) FROM SANPHAM
JOIN CTHD ON CTHD.MASP=SANPHAM.MASP
JOIN HOADON ON CTHD.SOHD=HOADON.SOHD
WHERE HOADON.NGHD BETWEEN '2006-1-1' AND '2006-12-31'

-- 22
SELECT MAX(TRIGIA) AS MAX_TRIGIA, MIN(TRIGIA) AS MIN_TRIGIA FROM HOADON;

-- 23
SELECT AVG(TRIGIA) AS AVG_TRIGIA FROM HOADON WHERE NGHD BETWEEN '2006-1-1' AND '2006-12-31'

-- 24
SELECT SUM(TRIGIA) AS DOANHTHU FROM HOADON WHERE NGHD BETWEEN '2006-1-1' AND '2006-12-31'

-- 25
SELECT SOHD FROM HOADON WHERE TRIGIA = (SELECT MAX(TRIGIA) AS MAX_TRIGIA FROM HOADON)

-- 26
SELECT KHACHHANG.HOTEN FROM HOADON 
JOIN KHACHHANG ON KHACHHANG.MAKH = HOADON.MAKH
WHERE HOADON.TRIGIA = (SELECT MAX(TRIGIA) AS MAX_TRIGIA FROM HOADON)

-- 27
SELECT TOP 3 HOADON.MAKH, KHACHHANG.HOTEN, SUM(HOADON.TRIGIA) AS DOANHTHU  FROM KHACHHANG
JOIN HOADON ON HOADON.MAKH=KHACHHANG.MAKH
GROUP BY HOADON.MAKH, KHACHHANG.HOTEN
ORDER BY DOANHTHU ASC;

-- 28
SELECT SANPHAM.MASP, SANPHAM.TENSP FROM SANPHAM
WHERE GIA IN
(SELECT TOP 3 SANPHAM.GIA FROM SANPHAM ORDER BY SANPHAM.GIA DESC)

-- 29
SELECT SANPHAM.MASP, SANPHAM.TENSP FROM SANPHAM
WHERE GIA IN
(SELECT TOP 3 SANPHAM.GIA FROM SANPHAM ORDER BY SANPHAM.GIA DESC)
AND SANPHAM.NUOCSX='Thai Lan'

-- 30
SELECT SANPHAM.MASP, SANPHAM.TENSP FROM SANPHAM
WHERE GIA IN
(SELECT TOP 3 SANPHAM.GIA FROM SANPHAM ORDER BY SANPHAM.GIA DESC)
AND SANPHAM.NUOCSX='Trung Quoc'

-- 31
SELECT TOP 3 HOADON.MAKH, KHACHHANG.HOTEN, SUM(HOADON.TRIGIA) AS DOANHSO  FROM KHACHHANG
JOIN HOADON ON HOADON.MAKH=KHACHHANG.MAKH
GROUP BY HOADON.MAKH, KHACHHANG.HOTEN
ORDER BY DOANHSO DESC;

-- 32
SELECT COUNT(*) FROM SANPHAM WHERE SANPHAM.NUOCSX='Trung Quoc';

-- 33
SELECT SANPHAM.NUOCSX, COUNT(*) as SANLUONG FROM SANPHAM GROUP BY SANPHAM.NUOCSX;

-- 34
SELECT SANPHAM.NUOCSX, MAX(SANPHAM.GIA) as MAX_GIA, MIN (SANPHAM.GIA) as MIN_GIA, AVG(SANPHAM.GIA) as AVG_GIA
FROM SANPHAM GROUP BY SANPHAM.NUOCSX;

-- 35
SELECT HOADON.NGHD, SUM(HOADON.TRIGIA) AS DOANHTHU FROM HOADON
GROUP BY HOADON.NGHD;

-- 36
SELECT MASP, SUM(CTHD.SL) AS SOLUONG FROM CTHD
JOIN HOADON ON HOADON.SOHD=CTHD.SOHD
WHERE HOADON.NGHD BETWEEN '2006-10-1' AND '2006-10-31'
GROUP BY MASP;

-- 37
SELECT NAM = DATEPART(YEAR, HOADON.NGHD), THANG=DATEPART(MONTH, HOADON.NGHD), 
SUM(HOADON.TRIGIA) FROM HOADON
WHERE HOADON.NGHD BETWEEN '2006-1-1' AND '2006-12-31'
GROUP BY DATEPART(YEAR, HOADON.NGHD), DATEPART(MONTH, HOADON.NGHD);

-- 38
SELECT CTHD.SOHD, COUNT(DISTINCT CTHD.MASP) AS SOLUONG FROM HOADON
JOIN CTHD ON CTHD.SOHD=HOADON.SOHD
GROUP BY CTHD.SOHD HAVING COUNT(DISTINCT CTHD.MASP) >= 4;

-- 39
SELECT HOADON.SOHD, COUNT(DISTINCT CTHD.MASP) FROM HOADON
JOIN CTHD ON CTHD.SOHD=HOADON.SOHD
JOIN SANPHAM ON SANPHAM.MASP=CTHD.MASP
WHERE NUOCSX='Viet Nam'
GROUP BY HOADON.SOHD HAVING COUNT(*) = 3;

-- 40
SELECT TOP 1 KHACHHANG.MAKH, KHACHHANG.HOTEN, COUNT(*) AS SOLANMH FROM KHACHHANG
JOIN HOADON ON HOADON.MAKH=KHACHHANG.MAKH
GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
ORDER BY SOLANMH DESC;

-- 41
SELECT THANG=DATEPART(MONTH, HOADON.NGHD), 
SUM(HOADON.TRIGIA) AS DOANHSO FROM HOADON
WHERE HOADON.NGHD BETWEEN '2006-1-1' AND '2006-12-31'
GROUP BY DATEPART(YEAR, HOADON.NGHD), DATEPART(MONTH, HOADON.NGHD)
HAVING SUM(HOADON.TRIGIA)=(
    SELECT MAX(DOANHSO_BH.DOANHSO) FROM (
    SELECT NAM = DATEPART(YEAR, HOADON.NGHD), THANG=DATEPART(MONTH, HOADON.NGHD), 
    SUM(HOADON.TRIGIA) AS DOANHSO FROM HOADON
    WHERE HOADON.NGHD BETWEEN '2006-1-1' AND '2006-12-31'
    GROUP BY DATEPART(YEAR, HOADON.NGHD), DATEPART(MONTH, HOADON.NGHD) 
    ) DOANHSO_BH
)

-- 42
SELECT SANPHAM.MASP, SANPHAM.TENSP, SUM(CTHD.SL) AS SOLUONG FROM SANPHAM
JOIN CTHD ON CTHD.MASP=SANPHAM.MASP
GROUP BY SANPHAM.MASP, SANPHAM.TENSP HAVING SUM(CTHD.SL)=(SELECT MIN(SOLUONGBANRA) FROM (
SELECT SANPHAM.MASP, SUM(CTHD.SL) AS SOLUONGBANRA FROM SANPHAM
JOIN CTHD ON CTHD.MASP=SANPHAM.MASP
GROUP BY SANPHAM.MASP) SLSP)

-- 43
SELECT * FROM SANPHAM
JOIN (SELECT SANPHAM.NUOCSX, MAX(GIA) AS GIALONNHAT FROM SANPHAM
GROUP BY SANPHAM.NUOCSX) GIALONNHAT_CACNUOC ON SANPHAM.NUOCSX = GIALONNHAT_CACNUOC.NUOCSX
WHERE SANPHAM.GIA=GIALONNHAT_CACNUOC.GIALONNHAT;

-- 44
SELECT NUOCSX, COUNT(DISTINCT GIA) AS GIABAN FROM SANPHAM
GROUP BY NUOCSX HAVING COUNT(DISTINCT GIA) >= 3;

-- 45
SELECT TOP 10 HOADON.MAKH, KHACHHANG.HOTEN, SUM(HOADON.TRIGIA) AS DOANHSO  FROM KHACHHANG
JOIN HOADON ON HOADON.MAKH=KHACHHANG.MAKH
JOIN (SELECT TOP 1 KHACHHANG.MAKH, KHACHHANG.HOTEN, COUNT(*) AS SOLANMH FROM KHACHHANG
JOIN HOADON ON HOADON.MAKH=KHACHHANG.MAKH
GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
ORDER BY SOLANMH DESC) MUAHANGNHIEUNHAT ON MUAHANGNHIEUNHAT.MAKH=HOADON.MAKH
GROUP BY HOADON.MAKH, KHACHHANG.HOTEN
ORDER BY DOANHSO DESC





